PatientReport/Models/Masters/AppSettingModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DataLayer;

namespace PatientReport.Models.Masters
{
    public class AppSettingModel:AppointmentSetting
    {
    }
}

PatientReport/Models/Masters/DepartmentModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PatientReport.Models.Masters
{
    public class DepartmentModel
    {
        public int DepartmentId { get; set; }
        public string DeparmentName { get; set; }
        public string DepartmentUrl { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public byte[] Image { get; set; }
    }

    public class DoctorModel
    {
        public int DoctorId { get; set; }
        public string DoctorName { get; set; }
        public int DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public string Designation { get; set; }
        public string Degree { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public byte[] Image { get; set; }
    }
    public class DoctorTypeModel
    {
        public int Id { get; set; }
        public string DoctorType { get; set; }
    }
        public class MasterLookupModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
    }
}

PatientReport/Models/Masters/ScheduleModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PatientReport.Models.Masters
{
    public class ScheduleModel
    {
        public int ScheduleId { get; set; }
        public int DoctorId { get; set; }
        public int DayId { get; set; }
        public int TimeFrom { get; set; }
        public int TimeFromMeridiumId { get; set; }
        public int TimeTo { get; set; }
        public int TimeToMeridiumId { get; set; }

    }
}

PatientReport/Controllers/MastersController.cs
using PatientReport.BAL.Masters;
using PatientReport.Infrastructure.Authentication;
using PatientReport.Models.PatientReport;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;
using DataLayer;
using PatientReport.Global;
using System.IO;
using PatientReport.Infrastructure.Adapter.WebService;

namespace PatientReport.Controllers
{
    public class MastersController : CommonController
    {
        public ActionResult HomePage()
        {
            return View();
        }

        public ActionResult PatientList()
        {
            return View();
        }
        [HttpPost]
        public JsonResult PatientList(string patienttype)
        {
            var userInfo = User as CustomPrincipal;
            if (userInfo != null)
            {
                int doctorId = userInfo.Id;
                if (patienttype == "IPD")
                {
                    List<IPDListResponseModel> loginResponseModel = new List<IPDListResponseModel>();
                    using (var client = new HttpClient())
                    {
                        client.BaseAddress = new Uri(ConfigurationManager.AppSettings["HIMSDoctorApiBaseUrl"].ToString());
                        client.DefaultRequestHeaders.Accept.Clear();
                        client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                        var response = client.GetAsync("/RMLAPI/api/PatientDetails/GetIpdList?doctid=" + doctorId + "").Result;
                        if (response.IsSuccessStatusCode)
                        {
                            string responseString = response.Content.ReadAsStringAsync().Result;
                            loginResponseModel = response.Content.ReadAsAsync<List<IPDListResponseModel>>().Result;
                        }
                    }
                    return Json(loginResponseModel);
                }
                else if (patienttype == "OPD")
                {
                    List<OPDListResponseModel> loginResponseModel = new List<OPDListResponseModel>();
                    using (var client = new HttpClient())
                    {
                        client.BaseAddress = new Uri(ConfigurationManager.AppSettings["HIMSDoctorApiBaseUrl"].ToString());
                        client.DefaultRequestHeaders.Accept.Clear();
                        client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                        var response = client.GetAsync("/RMLAPI/api/PatientDetails/GetOpdList?doctid=" + doctorId + "").Result;
                        if (response.IsSuccessStatusCode)
                        {
                            string responseString = response.Content.ReadAsStringAsync().Result;
                            loginResponseModel = response.Content.ReadAsAsync<List<OPDListResponseModel>>().Result;
                        }
                        else
                        {
                            return Json("ServerError");
                        }
                    }
                    return Json(loginResponseModel);
                }
            }
            else
            {
                return Json("Session Out");
            }
            return null;
        }

        public ActionResult PatientDetail(string crNumber)
        {
            crNumber = crNumber.Replace('~', ':').Replace('_', '/');
            DocumentDetails details = new DocumentDetails();
            ViewData["documents"] = details.GetAllDocumentDetail(crNumber);
            TempData["crNumber"] = crNumber;
            return View();
        }

        [HttpPost]
        public JsonResult PatientListBYCRNumber(string crNumber)
        {
            crNumber = crNumber.Replace('~', ':').Replace('_', '/');
            DocumentDetails details = new DocumentDetails();

            WebServiceIntegration service = new WebServiceIntegration();
            var patient = service.GetPatientInfoBYCRNumber(crNumber);
            if (patient != null)
            {
                return Json(patient);
            }
            return Json("NoPatient");
        }

        [HttpPost]
        public ActionResult PatientDetail(string title, string DocType, HttpPostedFileBase document)
        {
            PatientDocument PatientDocument = new PatientDocument();
            if (document != null && document.ContentLength > 0)
            {
                string fileUrl = getDocumentPath(document, Convert.ToString(TempData["crNumber"]).Replace(':', '~').Replace('/', '_'));

                PatientDocument.DocumentTitle = title;
                PatientDocument.DocumentType = DocType;
                PatientDocument.CRNumber = Convert.ToString(TempData["crNumber"]);
                PatientDocument.DocumentPath = fileUrl;
                //save file start
                //hospital.HospitalLogo = new byte[File1.ContentLength];
                //File1.InputStream.Read(hospital.HospitalLogo, 0, File1.ContentLength);
                //Use Namespace called :  System.IO  
                if (document.ContentLength > 0)
                {
                    DocumentDetails details = new DocumentDetails();
                    var result = details.SaveDocumentDetail(PatientDocument);
                    if (result == Enums.CrudStatus.DataAlreadyExist)
                    {
                        SetAlertMessage("Document already exist with same name", "Document Entry");
                    }
                    else
                    {
                        document.SaveAs(Server.MapPath(fileUrl));
                        SetAlertMessage("Document saved Successfully", "Document Entry");
                    }

                    return RedirectToAction("PatientDetail", new { crNumber = Convert.ToString(TempData["crNumber"]) });
                }
                else
                {
                    SetAlertMessage("document detail not saved", "Document Entry");
                    return RedirectToAction("PatientDetail", new { crNumber = Convert.ToString(TempData["crNumber"]) });
                }
            }
            else
            {
                SetAlertMessage("document detail not saved", "Document Entry");
                return RedirectToAction("PatientDetail", new { crNumber = Convert.ToString(TempData["crNumber"]) });
            }
        }

        private string getDocumentPath(HttpPostedFileBase document, string CRNumber)
        {
            string dirUrl = "~/PatientDocument/" + CRNumber;
            string dirPath = Server.MapPath(dirUrl);
            if (!Directory.Exists(dirPath))
            {
                Directory.CreateDirectory(dirPath);
            }
            // save the file to the Specifyed folder  
            string fileUrl = dirUrl + "/" + Path.GetFileName(document.FileName);
            return fileUrl;
        }

        public ActionResult UploadDocument()
        {
            return View();
        }
        public ActionResult SearchPatient()
        {
            return View();
        }

        public ActionResult Logout()
        {
            Session.Abandon();
            Session.Clear();
            return RedirectToAction("Index", "Login");
        }

    }
}

PatientReport/Views/Masters/AddDoctorLeave.cshtml
@{
    ViewBag.Title = "AddDoctorLeave";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/App/Masters/DoctorLeave.js"></script>
<div class="">
    <div class="col-sm-12 col-lg-12" style="padding-top:20px;">
        <div class="panel panel-primary">
            <div class="panel-heading">Find Patient Type</div>
            <div class="panel-body">
                <div class="col-container">
                    <div class="col">
                        <select class="form-control" id="ddlDepartments" name="departmentid" required="required">
                            <option value="">Select Patient Type</option>
                        </select>
                    </div>
                    <div class="col">
                        <select class="form-control" id="ddlDoctors" name="doctorid" required="required">
                            <option value="">Select Patient</option>
                        </select>
                    </div>

                    @*<div class="col">
                        <input class="form-control" type="date" id="txtleavedate" name="leavedate" required="required" />
                    </div>*@

                    <div class="col">
                        <button class="btn btn-primary" id="btnSave">Search</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-lg-12" style="padding-top:20px;">
        <div class="panel panel-primary">
            <div class="panel-heading">Patient Details</div>
            <div class="panel-body">
                <div class="table table-responsive">
                    <table class="table table-bordered table-hover table-responsive text-center" id="docTable">
                        <thead>
                            <tr>
                                <th style="width:10%">Sr. No.</th>
                                <th name="DoctorName">Registration/CR N0</th>
                                <th name="DoctorName">Patient Name</th>
                                <th name="DoctorName">Fathers Name</th>
                                <th name="DoctorName">Department Name</th>
                                <th name="DoctorName">EmailId</th>
                                <th name="DoctorName">Mobile No</th>
                                <th name="DoctorName">Action</th>
                                <th style="width:20%">Document Format</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr><td colspan="4">No Record Found</td></tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    .col-container {
        display: table; /* Make the container element behave like a table */
        width: 100%; /* Set full-width to expand the whole page */
    }

    .col {
        display: table-cell; /* Make elements inside the container behave like table cells */
        width:25%;
    }

        .col select,input {
            width: 95% !important;
        }
</style>

PatientReport/Views/Masters/HomePage.cshtml
@{
    ViewBag.Title = "HomePage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>HomePage</h2>

PatientReport/Views/Masters/PatientDetail.cshtml
@using DataLayer
@{
    ViewBag.Title = "PatientDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row" style="margin-top:50px;">
    <div class="col-sm-12 col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">Document Upload for Patient</div>
            <div class="panel-body">
                @using (Html.BeginForm("PatientDetail", "Masters", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <div class="container">
                        <table style="width:100%">
                            <tr>
                                <td style="width:30%">
                                    <label>Document Title</label>
                                    <input type="text" name="title" id="title" style="width: 100%;" required />
                                </td>
                                <td style="width:30%">
                                    <label>Document Type</label>
                                    <select class="form-control" style="width: 100%;" id="doctype" name="DocType" required="required">
                                        <option value="0">Select Document Type</option>
                                        <option value="PDF">PDF</option>
                                        <option value="Doc">Doc</option>
                                        <option value="Image">Image</option>
                                        <option value="Other">Other</option>
                                    </select>
                                </td>
                                <td style="width:30%">
                                    <label>Document</label>
                                    <input type="file" name="document" id="document" style="width: 100%;" required />
                                    <br />
                                </td>
                                <td style="width:10%">
                                    <input type="submit" name="Upload" class="btn btn-primary btn-blue btn-block btn-lg" value="Upload" style="width:100px;">
                                </td>
                            </tr>
                        </table>
                    </div>
                }
                <hr />
                <div class="container">
                    <table style="width:100%;">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Document Title</th>
                                <th>Document Type</th>
                                <th>Document</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                var documents = (List<PatientDocument>)(ViewData["documents"]);
                                if (documents != null)
                                {
                                    foreach (var document in documents)
                                    {
                                        <tr>
                                            <td>
                                                @document.Id
                                            </td>
                                            <td>
                                                @document.DocumentTitle
                                            </td>
                                            <td>
                                                @document.DocumentType
                                            </td>
                                            <td>
                                                @{
                                                    string baseUrl = Request.Url.Scheme + "://" + Request.Url.Authority + Request.ApplicationPath.TrimEnd('/') + "/";
                                                    string fileURL = baseUrl + @document.DocumentPath.Replace("~/", "");
                                                    <a class="navbar-brand" href="@fileURL" style="font-size:15px;color:#3838e8;" target="_blank">
                                                        @if (!string.IsNullOrEmpty(document.DocumentPath))
                                                        {
                                                            @document.DocumentPath.Substring(@document.DocumentPath.LastIndexOf('/') + 1, @document.DocumentPath.Length - @document.DocumentPath.LastIndexOf('/') - 1)
                                                        }
                                                    </a>
                                                }

                                            </td>
                                            <td>
                                                <a class="navbar-brand" href="/Masters/DeleteHospital/@document.Id" style="font-size:15px;color: red;">Delete</a>
                                                @*@Html.ActionLink("Delete", "DeleteHospital", "Masters", new { Id = document.Id }, new { @class = "navbar-brand" })*@
                                            </td>
                                        </tr>
                                    }
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>

PatientReport/Views/Masters/PatientList.cshtml
@{
    ViewBag.Title = "PatientList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/App/Masters/PatientList.js"></script>
<div class="">
    <div class="col-sm-12 col-lg-12" style="padding-top:20px;">
        <div class="panel panel-primary">
            <div class="panel-heading">Patient Type</div>
            <div class="panel-body">
                <div class="col-container">
                    <div class="col">
                        <select class="form-control" id="ddlPatientType" name="departmentid" required="required">
                            <option value="">Select Patient Type</option>
                            <option value="OPD">OPD</option>
                            <option value="IPD">IPD</option>
                        </select>
                    </div>
                    <div class="col">
                        <button class="btn btn-primary" id="btnSearch">Search</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-lg-12 hidden" style="padding-top:20px;" id="tablePatient">
        <div class="panel panel-primary">
            <div class="panel-heading" id="reportdetail">Patient Details</div>
            <div class="panel-body">
                <div class="table table-responsive">
                    <table class="table table-bordered table-hover table-responsive text-center" id="docTable">
                        <thead>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <span id="noRecordFound" class="hidden">No Record Found...</span>
</div>
<style>
    .col-container {
        display: table; /* Make the container element behave like a table */
        width: 100%; /* Set full-width to expand the whole page */
    }

    .col {
        display: table-cell; /* Make elements inside the container behave like table cells */
        width: 25%;
    }

        .col select, input {
            width: 95% !important;
        }
</style>

PatientReport/Views/Masters/SearchPatient.cshtml
@{
    ViewBag.Title = "SearchPatient";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/App/Masters/PatientList.js"></script>
<div class="">
    <div class="col-sm-12 col-lg-12" style="padding-top:20px;">
        <div class="panel panel-primary">
            <div class="panel-heading">Enter Patient CR Number</div>
            <div class="panel-body">
                <div class="col-container">
                    <div class="col">
                        <input type="text" name="crNumber" id="crNumber" value="" />
                    </div>
                    <div class="col">
                        <button class="btn btn-primary" id="btnSearchPatientEmployee">Search</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-lg-12 hidden" style="padding-top:20px;" id="tablePatient">
        <div class="panel panel-primary">
            <div class="panel-heading" id="reportdetail">Patient Details</div>
            <div class="panel-body">
                <div class="table table-responsive" style="max-width: 1086px;overflow-y: hidden;">
                    <table class="table table-bordered table-hover table-responsive text-center" id="docTable">
                        <thead>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <span id="noRecordFound" class="hidden">No Record Found...</span>
</div>
<style>
    .col-container {
        display: table; /* Make the container element behave like a table */
        width: 100%; /* Set full-width to expand the whole page */
    }

    .col {
        display: table-cell; /* Make elements inside the container behave like table cells */
        width: 25%;
    }

        .col select, input {
            width: 95% !important;
        }
</style>

PatientReport/Views/Masters/UploadDocument.cshtml
@{
    ViewBag.Title = "UploadDocument";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>UploadDocument</h2>